USE [ADM_IWS]
GO

/****** Object:  View [dbo].[vw_DataIWSReqEfis]    Script Date: 3/9/2017 10:10:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[vw_DataIWSReqEfis]
AS
SELECT        INVOICEID, RECEIVINGDATE, STATUS, ACTIVITY, INVOICEDATE, VENDORID, VENDORNAME, TAXVOUCHERNO, INVOICENO, PPN, MODIFIEDON
FROM            (
SELECT        INV.INVOICEID, INV.INVRECEIVEDATE AS RECEIVINGDATE, TXV.STATUS, TXV.ACTIVITY, INV.INVOICEDATE, INV.VENDORID, VEN.VENDORNAME, TXV.TAXVOUCHERNO, INV.INVOICENO, TXV.PPN,TXV.LASTUPDATEDON as 'MODIFIEDON' 
FROM            dbo.INVOICE AS INV INNER JOIN
dbo.TAXVOUCHER AS TXV ON TXV.INVOICEID = INV.INVOICEID INNER JOIN
dbo.MS_VENDOR AS VEN ON VEN.VENDORID = INV.VENDORID
WHERE        (TXV.STATUS = 'Received')

) AS InvoiceData


GO


