//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFakturADM.Web.ADDataService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ADService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GGIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GGI {
            get {
                return this.GGIField;
            }
            set {
                if ((object.ReferenceEquals(this.GGIField, value) != true)) {
                    this.GGIField = value;
                    this.RaisePropertyChanged("GGI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ADDataService.IADDataService")]
    public interface IADDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADDataService/AuthenticateUser", ReplyAction="http://tempuri.org/IADDataService/AuthenticateUserResponse")]
        eFakturADM.Web.ADDataService.User AuthenticateUser(string GGI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADDataService/SearchPersonByName", ReplyAction="http://tempuri.org/IADDataService/SearchPersonByNameResponse")]
        eFakturADM.Web.ADDataService.User SearchPersonByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADDataService/SearchPersonByNameBulk", ReplyAction="http://tempuri.org/IADDataService/SearchPersonByNameBulkResponse")]
        eFakturADM.Web.ADDataService.User[] SearchPersonByNameBulk(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IADDataServiceChannel : global::eFakturADM.Web.ADDataService.IADDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ADDataServiceClient : System.ServiceModel.ClientBase<global::eFakturADM.Web.ADDataService.IADDataService>, global::eFakturADM.Web.ADDataService.IADDataService {
        
        public ADDataServiceClient() {
        }
        
        public ADDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ADDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eFakturADM.Web.ADDataService.User AuthenticateUser(string GGI) {
            return base.Channel.AuthenticateUser(GGI);
        }
        
        public eFakturADM.Web.ADDataService.User SearchPersonByName(string name) {
            return base.Channel.SearchPersonByName(name);
        }
        
        public eFakturADM.Web.ADDataService.User[] SearchPersonByNameBulk(string name) {
            return base.Channel.SearchPersonByNameBulk(name);
        }
    }
}
