//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MSDS_GenericSOAP", Namespace="http://www.example.org/MSDS_Generic/")]
public partial class MSDS_Generic : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback MSDS_GetListOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetMSDSChapterOperationCompleted;
    
    /// <remarks/>
    public MSDS_Generic() {
        this.Url = "http://idepbpn-uam901:7001/eFakturADMIH/Proxy_Services/MSDSService";
    }
    
    /// <remarks/>
    public event MSDS_GetListCompletedEventHandler MSDS_GetListCompleted;
    
    /// <remarks/>
    public event GetMSDSChapterCompletedEventHandler GetMSDSChapterCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/MSDS_Generic/MSDS_GetList", RequestElementName="MSDS_Generic", RequestNamespace="http://www.example.org/MSDS_Generic/", ResponseElementName="MSDS_GenericResponse", ResponseNamespace="http://www.example.org/MSDS_Generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("MSDS_Generic.Response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute("MSDS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public itemType[] MSDS_GetList([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] MSDS_GenericMSDS_GenericType MSDS_GenericType, [System.Xml.Serialization.XmlAttributeAttribute()] out string cid) {
        object[] results = this.Invoke("MSDS_GetList", new object[] {
                    MSDS_GenericType});
        cid = ((string)(results[1]));
        return ((itemType[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMSDS_GetList(MSDS_GenericMSDS_GenericType MSDS_GenericType, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MSDS_GetList", new object[] {
                    MSDS_GenericType}, callback, asyncState);
    }
    
    /// <remarks/>
    public itemType[] EndMSDS_GetList(System.IAsyncResult asyncResult, out string cid) {
        object[] results = this.EndInvoke(asyncResult);
        cid = ((string)(results[1]));
        return ((itemType[])(results[0]));
    }
    
    /// <remarks/>
    public void MSDS_GetListAsync(MSDS_GenericMSDS_GenericType MSDS_GenericType) {
        this.MSDS_GetListAsync(MSDS_GenericType, null);
    }
    
    /// <remarks/>
    public void MSDS_GetListAsync(MSDS_GenericMSDS_GenericType MSDS_GenericType, object userState) {
        if ((this.MSDS_GetListOperationCompleted == null)) {
            this.MSDS_GetListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMSDS_GetListOperationCompleted);
        }
        this.InvokeAsync("MSDS_GetList", new object[] {
                    MSDS_GenericType}, this.MSDS_GetListOperationCompleted, userState);
    }
    
    private void OnMSDS_GetListOperationCompleted(object arg) {
        if ((this.MSDS_GetListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.MSDS_GetListCompleted(this, new MSDS_GetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/MSDS_Generic/GetMSDSChapter", RequestNamespace="http://www.example.org/MSDS_Generic/", ResponseNamespace="http://www.example.org/MSDS_Generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute("MSDSChapter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public chapterType[] GetMSDSChapter([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string MSDSID) {
        object[] results = this.Invoke("GetMSDSChapter", new object[] {
                    MSDSID});
        return ((chapterType[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetMSDSChapter(string MSDSID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetMSDSChapter", new object[] {
                    MSDSID}, callback, asyncState);
    }
    
    /// <remarks/>
    public chapterType[] EndGetMSDSChapter(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((chapterType[])(results[0]));
    }
    
    /// <remarks/>
    public void GetMSDSChapterAsync(string MSDSID) {
        this.GetMSDSChapterAsync(MSDSID, null);
    }
    
    /// <remarks/>
    public void GetMSDSChapterAsync(string MSDSID, object userState) {
        if ((this.GetMSDSChapterOperationCompleted == null)) {
            this.GetMSDSChapterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMSDSChapterOperationCompleted);
        }
        this.InvokeAsync("GetMSDSChapter", new object[] {
                    MSDSID}, this.GetMSDSChapterOperationCompleted, userState);
    }
    
    private void OnGetMSDSChapterOperationCompleted(object arg) {
        if ((this.GetMSDSChapterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetMSDSChapterCompleted(this, new GetMSDSChapterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/MSDS_Generic/")]
public partial class MSDS_GenericMSDS_GenericType {
    
    private string mATERIALNAMEField;
    
    private string mSDSIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MATERIALNAME {
        get {
            return this.mATERIALNAMEField;
        }
        set {
            this.mATERIALNAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSDSID {
        get {
            return this.mSDSIDField;
        }
        set {
            this.mSDSIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/MSDS_Generic/")]
public partial class chapterType {
    
    private string mSDSIDField;
    
    private string cHAPTERIDField;
    
    private string tEXTSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSDSID {
        get {
            return this.mSDSIDField;
        }
        set {
            this.mSDSIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CHAPTERID {
        get {
            return this.cHAPTERIDField;
        }
        set {
            this.cHAPTERIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TEXTS {
        get {
            return this.tEXTSField;
        }
        set {
            this.tEXTSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/MSDS_Generic/")]
public partial class itemType {
    
    private string idField;
    
    private string aCTIVE_STSField;
    
    private string aTTACHMENTField;
    
    private string dESCRIPTIONField;
    
    private string lAST_UPDATEField;
    
    private string mATERIAL_IDField;
    
    private string mATERIAL_NAMEField;
    
    private string nPA_FIRE_HZDField;
    
    private string nPA_HEALTH_HZDField;
    
    private string nPA_REACT_HZDField;
    
    private string nPA_SPEC_HZDField;
    
    private string sUPPLIER_NBRField;
    
    private string pURPOSEField;
    
    private string aPPROVAL_STS_IDField;
    
    private string sUPPLIER_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ACTIVE_STS {
        get {
            return this.aCTIVE_STSField;
        }
        set {
            this.aCTIVE_STSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ATTACHMENT {
        get {
            return this.aTTACHMENTField;
        }
        set {
            this.aTTACHMENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LAST_UPDATE {
        get {
            return this.lAST_UPDATEField;
        }
        set {
            this.lAST_UPDATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MATERIAL_ID {
        get {
            return this.mATERIAL_IDField;
        }
        set {
            this.mATERIAL_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MATERIAL_NAME {
        get {
            return this.mATERIAL_NAMEField;
        }
        set {
            this.mATERIAL_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NPA_FIRE_HZD {
        get {
            return this.nPA_FIRE_HZDField;
        }
        set {
            this.nPA_FIRE_HZDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NPA_HEALTH_HZD {
        get {
            return this.nPA_HEALTH_HZDField;
        }
        set {
            this.nPA_HEALTH_HZDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NPA_REACT_HZD {
        get {
            return this.nPA_REACT_HZDField;
        }
        set {
            this.nPA_REACT_HZDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NPA_SPEC_HZD {
        get {
            return this.nPA_SPEC_HZDField;
        }
        set {
            this.nPA_SPEC_HZDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUPPLIER_NBR {
        get {
            return this.sUPPLIER_NBRField;
        }
        set {
            this.sUPPLIER_NBRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PURPOSE {
        get {
            return this.pURPOSEField;
        }
        set {
            this.pURPOSEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APPROVAL_STS_ID {
        get {
            return this.aPPROVAL_STS_IDField;
        }
        set {
            this.aPPROVAL_STS_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUPPLIER_ID {
        get {
            return this.sUPPLIER_IDField;
        }
        set {
            this.sUPPLIER_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void MSDS_GetListCompletedEventHandler(object sender, MSDS_GetListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MSDS_GetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal MSDS_GetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public itemType[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((itemType[])(this.results[0]));
        }
    }
    
    /// <remarks/>
    public string cid {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetMSDSChapterCompletedEventHandler(object sender, GetMSDSChapterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetMSDSChapterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetMSDSChapterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public chapterType[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((chapterType[])(this.results[0]));
        }
    }
}
